log:
  level: debug
  disable_sentry: true

db:
  url: postgres://users:users@localhost:5555/users?sslmode=disable #example

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: GiAuth
  service_port: 80

jwt:
  secret_key: "TkuYzT5B+R+EhAtGoqsFYnXIiOxDUuiBF722CZFOnRc=" #example
  expiration_time: 24h

email:
  password: "secret"
  email: "example@gmail.com"