-- +migrate Up
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS USERS (
   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
   username VARCHAR(150) UNIQUE NOT NULL,
   first_name VARCHAR(100) NOT NULL,
   last_name VARCHAR(100) NOT NULL,
   middle_name VARCHAR(100),
   email VARCHAR(255) UNIQUE NOT NULL,
   email_status BOOLEAN NOT NULL DEFAULT FALSE,
   two_factor_auth BOOLEAN NOT NULL DEFAULT FALSE,
   password_hash VARCHAR(255) NOT NULL,
   secret_key VARCHAR(255),
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- +migrate Down
DROP TABLE IF EXISTS USERS;
